//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Nana/Challenge1/Settings/MyInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInput"",
    ""maps"": [
        {
            ""name"": ""MacOS"",
            ""id"": ""209f132d-c98a-4710-8065-c231222f8320"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""3bc117fc-89f9-4c19-a3b9-9cf6a049a4cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Button"",
                    ""id"": ""15ff903f-5426-46ac-a651-81967df26333"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""76d5b9af-712b-459f-a57b-dfad4de1ab10"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3eeab24e-a4f3-4d06-9ab5-bda117d72d6e"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MacOS
        m_MacOS = asset.FindActionMap("MacOS", throwIfNotFound: true);
        m_MacOS_Jump = m_MacOS.FindAction("Jump", throwIfNotFound: true);
        m_MacOS_MousePosition = m_MacOS.FindAction("MousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MacOS
    private readonly InputActionMap m_MacOS;
    private List<IMacOSActions> m_MacOSActionsCallbackInterfaces = new List<IMacOSActions>();
    private readonly InputAction m_MacOS_Jump;
    private readonly InputAction m_MacOS_MousePosition;
    public struct MacOSActions
    {
        private @MyInput m_Wrapper;
        public MacOSActions(@MyInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_MacOS_Jump;
        public InputAction @MousePosition => m_Wrapper.m_MacOS_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_MacOS; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MacOSActions set) { return set.Get(); }
        public void AddCallbacks(IMacOSActions instance)
        {
            if (instance == null || m_Wrapper.m_MacOSActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MacOSActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IMacOSActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IMacOSActions instance)
        {
            if (m_Wrapper.m_MacOSActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMacOSActions instance)
        {
            foreach (var item in m_Wrapper.m_MacOSActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MacOSActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MacOSActions @MacOS => new MacOSActions(this);
    public interface IMacOSActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
